### ISSUE TITLE
Image caching do not work

### ISSUE THREAD

**Issue by Winkelried** [nkanaev/bubble#18] opened 2015-09-23 10:47 UTC
Hello,

I use an HP 8 1401 with android 4.2.2 and the and Bubble 1.3.0 (4).

Since it's the first time I use it, I suppose there would be picture in the rectangle of each comic/manga, but nop. Tried with zip and cbz archives.

**Comment by nkanaev** [comment] 2015-09-24 10:31
Can files be opened for reading? Would be glad if you could check rar archives as well.

**Comment by Winkelried** [comment] 2015-09-25 08:01
I also tried with an Alcatel Idol 2 Mini L running android 4.3 and I have the same problem.

I can open zip, cbz and normal folders but not rar-based one like cbr (and I do not get the picture with them as well).

**Comment by nkanaev** [comment] 2015-09-25 09:47
Ok, the problem is related to the [cache directory](http://developer.android.com/intl/ru/reference/android/content/Context.html#getExternalCacheDir()) being unavailable, caused by either external storage absence, or lack of [writing permission](http://developer.android.com/intl/ru/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE). Will try to fix it by the next release.

**Comment by nkanaev** [comment] 2016-01-02 14:07
@Winkelried could you please report if the issue has been resolved in v1.4.0?

**Comment by Winkelried** [comment] 2016-01-14 17:07
Yes it works with zip and rar archives. But I've noticied a new issue (shall I make a new issue ?). The other menu is visible.

![capture d ecran_2016-01-14-18-01-03](https://cloud.githubusercontent.com/assets/13598571/12331366/717821be-bae9-11e5-9f7b-dccb803b2a8e.png)

**Comment by nkanaev** [comment] 2016-01-14 17:58
yes, report the new issue.

**Closed** 2016-01-20 10:07 UTC
